import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'wouter';
import { LoginForm } from '@/components/auth/LoginForm';
import { SignupForm } from '@/components/auth/SignupForm';
import { Button } from '@/components/ui/button';
export default function AuthPage() {
    const [isLogin, setIsLogin] = useState(true);
    return (_jsxs("div", { className: "min-h-screen bg-white", children: [_jsxs("div", { className: "bg-gray-800 text-white text-sm px-4 py-1 flex justify-between items-center", children: [_jsx("span", { className: "text-sm", children: "9:41" }), _jsxs("div", { className: "flex items-center space-x-1", children: [_jsx("div", { className: "w-1 h-1 bg-gray-400 rounded-full" }), _jsx("div", { className: "w-1 h-1 bg-gray-400 rounded-full" }), _jsx("div", { className: "w-1 h-1 bg-gray-400 rounded-full" })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsxs("div", { className: "flex space-x-1", children: [_jsx("div", { className: "w-1 h-1 bg-white rounded-full" }), _jsx("div", { className: "w-1 h-1 bg-white rounded-full" }), _jsx("div", { className: "w-1 h-1 bg-white rounded-full" }), _jsx("div", { className: "w-1 h-1 bg-white rounded-full" })] }), _jsx("div", { className: "w-4 h-2 border border-white rounded-sm", children: _jsx("div", { className: "w-3 h-1 bg-white rounded-sm" }) })] })] }), _jsxs("div", { className: "flex flex-col items-center justify-center min-h-[calc(100vh-60px)] px-4 py-8", children: [_jsxs("div", { className: "text-center mb-12", children: [_jsx("div", { className: "flex items-center justify-center mb-4", children: _jsx("img", { src: "/stocksprout-logo.png", alt: "StockSprout Logo", className: "h-28 w-auto sm:h-36 md:h-40" }) }), _jsx("p", { className: "text-[10px] font-normal text-black", children: isLogin ? "Grow the future our kids deserve" : "Growing the future our kids deserve" })] }), isLogin ? (_jsx(LoginForm, { onSwitchToSignup: () => setIsLogin(false) })) : (_jsxs(_Fragment, { children: [_jsx(SignupForm, { onSwitchToLogin: () => setIsLogin(true) }), _jsx("div", { className: "text-center mt-6", children: _jsx(Button, { type: "button", variant: "link", className: "p-0 h-auto text-blue-600 font-medium", onClick: () => setIsLogin(true), children: "Already have an account? Sign in" }) })] })), _jsxs("div", { className: "mt-16 text-center text-xs text-gray-600 space-y-1", children: [_jsx("p", { children: "StockSprout LLC, Member NYSE, SIPC, FCC." }), _jsx("p", { children: "700 Sprout Street, Phoenix, AZ 85235" }), _jsx("p", { children: "\u00A92025, All rights reserved." }), _jsx(Link, { href: "/privacy-policy", children: _jsx("p", { className: "text-blue-600 cursor-pointer hover:text-blue-800", children: "Privacy Policy" }) })] })] })] }));
}
