import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const JourneyGraphic = ({ stages, childPositions, className = "" }) => {
    return (_jsx("div", { className: `relative w-full h-80 ${className}`, children: _jsxs("svg", { className: "absolute inset-0 w-full h-full", viewBox: "0 0 400 320", preserveAspectRatio: "xMidYMid meet", children: [_jsx("defs", { children: childPositions.map((c) => (_jsx("clipPath", { id: `avatar-clip-${c.childId}`, children: _jsx("circle", { cx: Math.round(c.position.x), cy: Math.round(c.position.y), r: "14" }) }, c.childId))) }), _jsx("path", { d: "M 80 250 L 280 250 Q 350 250 350 200 Q 350 150 280 150 L 120 150 Q 50 150 50 100 Q 50 50 120 50 L 320 50", fill: "none", stroke: "#D1D5DB", strokeWidth: "20", strokeLinecap: "round" }), stages.map((stage) => (_jsxs("g", { children: [_jsx("circle", { cx: stage.position.x, cy: stage.position.y, r: "20", fill: stage.color, stroke: "white", strokeWidth: "2" }), _jsx("foreignObject", { x: stage.position.x - 8, y: stage.position.y - 8, width: "16", height: "16", children: _jsx("div", { className: "flex items-center justify-center w-full h-full text-white", children: stage.icon }) }), _jsx("text", { x: stage.position.x, y: stage.position.y + 35, textAnchor: "middle", className: "text-xs font-medium fill-gray-700", fontSize: "10", children: stage.name })] }, stage.id))), childPositions.map((child) => {
                    const x = Math.round(child.position.x);
                    const y = Math.round(child.position.y);
                    return (_jsx("g", { children: child.avatarUrl ? (_jsxs(_Fragment, { children: [_jsx("image", { x: x - 14, y: y - 14, width: 28, height: 28, href: child.avatarUrl, preserveAspectRatio: "xMidYMid slice", clipPath: `url(#avatar-clip-${child.childId})` }), _jsx("circle", { cx: x, cy: y, r: "16", fill: "none", stroke: "#3B82F6", strokeWidth: "2" })] })) : (_jsxs(_Fragment, { children: [_jsx("circle", { cx: x, cy: y, r: "14", fill: "#E5E7EB", clipPath: `url(#avatar-clip-${child.childId})` }), _jsx("text", { x: x, y: y, textAnchor: "middle", dominantBaseline: "central", className: "text-sm font-medium fill-gray-600", fontSize: "12", children: child.childName.charAt(0) }), _jsx("circle", { cx: x, cy: y, r: "16", fill: "none", stroke: "#3B82F6", strokeWidth: "2" })] })) }, child.childId));
                })] }) }));
};
export default JourneyGraphic;
